Fixed bugs

diff --git a/bin/hlog b/bin/hlog
--- a/bin/hlog
+++ b/bin/hlog
@@ -25,10 +25,11 @@
 #L:  WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 #h: Usage:
 #h:      
-#h: $0 {error,info,warning} MESSAGE      : Print message.
-#h: $0 {debug}              MESSAGE      : Print message if $DEBUG is defined. 
-#h: $0 {fatal|abort}        MESSAGE      : Print message and fail.
-#h: $0 {errif}              MESSAGE TEST : Print message and fail if test succedes..
+#h: $0 {error,info,warning} MSG       : Print message.
+#h: $0 {debug}              MSG       : Print message if $DEBUG is defined. 
+#h: $0 {fatal|abort}        MSG       : Print message and fail.
+#h: $0 {errif}              MSG TEST  : Print message and fail if test succedes.
+#h: $0 {file}               NAME DESC : Prnt log filename.
 hlog() {
     local cmd="$1"
     shift
@@ -51,6 +52,12 @@ hlog() {
                  fi;;
         fatal)   hlog error "$*"; exit 1;;
         abort)   hlog error "$*"; exit 1;;
+        file)    local name="${1:-${SCRNAME}}"
+                 local name="`basename "${name}"`"
+                 mkdir -p "${HOME}/.log"
+                 echo "${SCRNAME}: [~/.log/${name}.log] ${2}" >&2
+                 echo "${HOME}/.log/${name}.log"
+                 ;;
         *)       hlog info "${cmd} $*";;
     esac
 }
diff --git a/bin/vcd b/bin/vcd
--- a/bin/vcd
+++ b/bin/vcd
@@ -38,7 +38,7 @@ vcd() {
         local d="$1"
     fi
     if test ! -n "${d}";then
-        echo "vcd [E]: Please specify a directory." >&2
+        echo "vcd: error: Didn't specify a directory." >&2
         return 1
     elif test @"${o}" = @"enter";then
         cd "${d}"
@@ -59,7 +59,8 @@ if test @"${SCRNAME}" = @"vcd";then
             sed -n 's/^ *#l: \{0,2\}//p' "$0"
             ;;
         *)
-            vcd "$@"
+            echo "vcd: error: Please source vcd before usage." >&2
+            exit 1
             ;;
     esac
 fi
